### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [7]:
vector = np.random.rand(10)
vector

array([0.91900263, 0.10320768, 0.4236045 , 0.60433086, 0.11119047,
       0.07908624, 0.26838123, 0.86114196, 0.62362376, 0.70669944])

In [6]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [14]:
vector_modified = np.round(vector + 10, 2)
vector_modified

array([10.92, 10.1 , 10.42, 10.6 , 10.11, 10.08, 10.27, 10.86, 10.62,
       10.71])

In [15]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [16]:
vector_squared = np.square(vector)
vector_squared

array([0.84456584, 0.01065182, 0.17944077, 0.36521579, 0.01236332,
       0.00625463, 0.07202848, 0.74156547, 0.3889066 , 0.49942411])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [17]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [20]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [23]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [24]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [25]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [27]:
vector

array([0.91900263, 0.10320768, 0.4236045 , 0.60433086, 0.11119047,
       0.07908624, 0.26838123, 0.86114196, 0.62362376, 0.70669944])

In [28]:
vector.T

array([0.91900263, 0.10320768, 0.4236045 , 0.60433086, 0.11119047,
       0.07908624, 0.26838123, 0.86114196, 0.62362376, 0.70669944])

 Транспортування не впливає на одновимірні вектори

In [30]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.91900263],
       [0.10320768],
       [0.4236045 ],
       [0.60433086],
       [0.11119047],
       [0.07908624],
       [0.26838123],
       [0.86114196],
       [0.62362376],
       [0.70669944]])

In [35]:
column_vector.shape

(10, 1)

numpy.expand_dims перетворила одновимірний вектор на двовимірній вектор-стовпчик

In [33]:
column_vector_T = column_vector.T
column_vector_T

array([[0.91900263, 0.10320768, 0.4236045 , 0.60433086, 0.11119047,
        0.07908624, 0.26838123, 0.86114196, 0.62362376, 0.70669944]])

In [34]:
column_vector_T.shape

(1, 10)

Транспортування вектора column_vector пертворило його знову на одновимірний вектор та повернуло його до початкової форми - вектора vector