### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [8]:
vector = np.random.rand(10)
vector, vector.shape

(array([0.33162085, 0.99116806, 0.40693125, 0.98429075, 0.91629099,
        0.44515178, 0.22988635, 0.90931829, 0.41118351, 0.78958194]),
 (10,))

In [9]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [12]:
vector_new = np.round(vector + 10, 2)
vector_new

array([10.33, 10.99, 10.41, 10.98, 10.92, 10.45, 10.23, 10.91, 10.41,
       10.79])

In [14]:
matrix_new = matrix * 2
matrix_new

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [21]:
vector_sqr = np.square(vector)
vector_sqr

array([0.10997239, 0.98241413, 0.16559304, 0.96882828, 0.83958918,
       0.1981601 , 0.05284774, 0.82685975, 0.16907188, 0.62343963])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [23]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [25]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [26]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [29]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [31]:
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [32]:
vector_T = vector.T
vector_T, vector_T.shape

(array([0.33162085, 0.99116806, 0.40693125, 0.98429075, 0.91629099,
        0.44515178, 0.22988635, 0.90931829, 0.41118351, 0.78958194]),
 (10,))

Транспортування не впливає на одновимірні вектори

In [38]:
column_vector = np.expand_dims(vector, 1)
vector, vector.shape, column_vector, column_vector.shape

(array([0.33162085, 0.99116806, 0.40693125, 0.98429075, 0.91629099,
        0.44515178, 0.22988635, 0.90931829, 0.41118351, 0.78958194]),
 (10,),
 array([[0.33162085],
        [0.99116806],
        [0.40693125],
        [0.98429075],
        [0.91629099],
        [0.44515178],
        [0.22988635],
        [0.90931829],
        [0.41118351],
        [0.78958194]]),
 (10, 1))

numpy.expand_dims перетворила одновимірний вектор на двовимірній вектор-стовпчик

In [39]:
column_vector_T = column_vector.T
column_vector_T, column_vector_T.shape

(array([[0.33162085, 0.99116806, 0.40693125, 0.98429075, 0.91629099,
         0.44515178, 0.22988635, 0.90931829, 0.41118351, 0.78958194]]),
 (1, 10))